# This is a basic workflow to help you get started with Actions

name: CallerWorkflow

# Controls when the workflow will run. Workflow runs when manually triggered using the UI or API.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      buildDifferentApp:
        # Friendly description to be shown in the UI instead of 'name'.
        description: 'Which programming language?'
        # Default value if no value is explicitly provided
        default: 'Go'
        # Input has to be provided for the worflow to run.
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  buildDifferentAppPlatform:
    if: ${{ github.evetn.inputs.buildDifferentApp == 'Go' }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    uses: FlowFactor2/mslearn-aks-deployment-pipeline-github-actions/.github/workflows/deploytoAksCluster.yml@main
    with: 
      username: WoutBeyens
    secrets:
      envPAT: ${{ secrets.envPAT }}
        
